# Name of your dbt project
name: "pr_ecom"
version: "1.0.0"
config-version: 2

# Ensure this matches the name in your profiles.yml
profile: "default"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring the Three-Tier Architecture
models:
  pr_ecom:
    # 1. RAW: Direct 1:1 views of the bigquery-public-data
    raw:
      +materialized: view
      +schema: raw
      +database: pr-ecom

    # 2. PREP: Cleaning, renaming, and basic logic
    prep:
      +materialized: view
      +schema: prep
      +database: pr-ecom

    # 3. SERVE: Final joined tables for BI & AI/Reporting
    serve:
      +materialized: table
      +schema: serve
      +database: pr-ecom
